### ISSUE TITLE
Porta 9103

### ISSUE THREAD

**Issue by anghos** [vaamonde/ubuntu-1804#7]
Olá Vaamonde,

Após a instalação reparei que a porta 9103 não subia, configurei o api e a console web normalmente.
Após tudo configurado verifiquei e o storage não sobe e a porta 9103 continua não sendo listada. Consegue me ajudar a solucionar este problema?
Obrigado!

**Comment by vaamonde** [comment]
Olá para melhor ajudá-lo, se você seguiu todos os procedimentos executando o meu script ou fazendo manual, manda os detalhes do arquivo de Log, segue um How-To que pode te ajudar caso você tenha outros problemas se tiver usando distribuições ou aplicativos diferentes: https://www.bacula.org/5.2.x-manuals/en/problems/problems.pdf

**Comment by anghos** [comment]
Olá,
Consegui resolver o problema refazendo o processo de instalação.

Porém agora me deparei com uma dúvida e não um problema em si.
Como configuro para que o bacula comunique com clientes externos da minha rede que respondem via DDNS?
Ao tentar realizar o backup destes clientes ele consegue comunicar com o client porém não consegue fazer o backup dos arquivos.
Meu servidor tem um IP fixo válido.
Na rede interna está funcionando perfeitamente.

**Comment by vaamonde** [comment]
Show, depois manda mais detalhes do problema, pois se o meu script estiver errado consigo verificar, testei novamente é está tudo OK, nesse caso recomendo o seguinte (vou ser sincero, ainda não executei esse procedimento para testar): Se você utiliza firewall precisa fazer o Port Forward das Portas do Bacula/Baculum para o seu servidor Interno, mais o melhor seria fechar uma VPN (IPSec ou OpenVPN) para isso.

**Comment by anghos** [comment]
Olá, consegui resolver esta questão também.
Como estou tentando buscar via ddns e não por vpn, tive que adicionar o meu ip válido na configuração do meu storage e redirecionando a porta 9103 para ele internamente. Pois quando o cliente for buscar o storage para realizar o backup, ele irá buscar o ip válido e assim consegui realizar o backup de forma efetiva.
Obrigado pelo apoio e conhecimento Vaamonde.
Qualquer dúvida volto a perguntar por aqui. :D

**Comment by vaamonde** [comment]
Show di bola!!!! Parabéns!!!! fica registrado aqui que funciona.... vou fechar o tópico, qualquer coisa só avisar, abraço e sucesso sempre é #BoraParaPratica
